name: veggo
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: ^3.5.3


#---------------------- PACKAGES --------------------------

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages   
  cupertino_icons: ^1.0.8

  # Smooth Page Indicator
  smooth_page_indicator: ^1.2.0+3

  # Shared Preferences for Local Storage
  shared_preferences: any

  # Permission Handler Device Permissions Services  
  permission_handler: ^11.3.1

  # SVG files Render
  flutter_svg: ^2.0.16
  http: ^1.2.2
  intl: ^0.20.1
  get: ^4.6.6



#---------------------- END PACKAGES ----------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true


#------------------------ Assets -------------------------

  assets:

    # Logos
    - assets/logos/

    # Icons 
    - assets/icons/location.svg
    
    # Images
    - assets/images/login.svg
    - assets/images/location.svg
    - assets/images/welcome_text.svg
    - assets/images/welcome.svg 

    # Videos
    - assets/videos/onboarding1.gif
    - assets/videos/onboarding2.gif
    - assets/videos/onboarding3.gif


  #------------------------ Local Fonts ----------------------
   
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Black.ttf
        weight: 900
      - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
        weight: 100
        style: italic
