name: veggo
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: ^3.5.3


#---------------------- PACKAGES --------------------------

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages   
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: any
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.16
  http: ^1.2.2
  intl: ^0.20.1
  flutter_native_splash: ^2.4.3
  provider: ^6.1.2
  country_picker: ^2.0.27
  pinput: ^5.0.0
  firebase_core: ^3.9.0
  firebase_analytics: ^11.3.6
  firebase_auth: ^5.3.4



#---------------------- END PACKAGES ----------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true


#------------------------ Assets -------------------------

  assets:

    # Logos
    - assets/logos/

    # Icons 
    - assets/icons/
    
    # Images
    - assets/images/

    # Videos
    - assets/videos/


  #------------------------ Local Fonts ----------------------
   
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Black.ttf
        weight: 900
      - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
        weight: 100
        style: italic
